# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{buzzsprout}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Wynn Netherland"]
  s.date = %q{2010-08-06}
  s.description = %q{Ruby wrapper for the stealth mode Buzzsprout API}
  s.email = %q{wynn.netherland@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".yardopts",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "buzzsprout.gemspec",
     "changelog.md",
     "lib/buzzsprout.rb",
     "lib/buzzsprout/client.rb",
     "lib/buzzsprout/episode.rb",
     "test/fixtures/episode.json",
     "test/fixtures/episode_list.json",
     "test/fixtures/tagged.json",
     "test/helper.rb",
     "test/test_buzzsprout.rb"
  ]
  s.homepage = %q{http://wynnnetherland.com/projects/buzzsprout}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Ruby wrapper for the stealth mode Buzzsprout API}
  s.test_files = [
    "test/helper.rb",
     "test/test_buzzsprout.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.2"])
      s.add_runtime_dependency(%q<hashie>, [">= 0.2.0"])
      s.add_runtime_dependency(%q<httparty>, [">= 0.5.0"])
      s.add_development_dependency(%q<shoulda>, [">= 2.10.1"])
      s.add_development_dependency(%q<jnunemaker-matchy>, ["= 0.4.0"])
      s.add_development_dependency(%q<fakeweb>, [">= 1.2.5"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, [">= 2.3.2"])
      s.add_dependency(%q<hashie>, [">= 0.2.0"])
      s.add_dependency(%q<httparty>, [">= 0.5.0"])
      s.add_dependency(%q<shoulda>, [">= 2.10.1"])
      s.add_dependency(%q<jnunemaker-matchy>, ["= 0.4.0"])
      s.add_dependency(%q<fakeweb>, [">= 1.2.5"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 2.3.2"])
    s.add_dependency(%q<hashie>, [">= 0.2.0"])
    s.add_dependency(%q<httparty>, [">= 0.5.0"])
    s.add_dependency(%q<shoulda>, [">= 2.10.1"])
    s.add_dependency(%q<jnunemaker-matchy>, ["= 0.4.0"])
    s.add_dependency(%q<fakeweb>, [">= 1.2.5"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

